# Generated by Django 3.1.5 on 2021-01-18 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_auto_20210110_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(null=True, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='post',
            name='_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', through='news.PostCategory', to='news.Category'),
        ),
    ]
