# Generated by Django 3.1.5 on 2021-01-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210118_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategorySubscribers',
        ),
    ]
